src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, make_response, url_for, redirect

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators
import src.models.stores.error as StoreErrors

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route("/")
def index():
    alerts = Alert.get_alerts()
    return render_template('alerts/alert_index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def create_alert():

    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/create_alert.html')
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])
        item_name = request.form['name']
        item_url = request.form['url']
        try:
            item = Item(item_name, item_url)
        except StoreErrors.StoreError as e:
            return e.message
        #get the user details from DB by session email
        user_email = session['email']

        # create the new blog in DB
        new_alert = Alert(user_email, price_limit, item._id)

        new_alert.load_item_price()


        # save to DB only after alert was created
        item.save_to_mongo()

        # will prepare the data of existing alert - based on above method
        return make_response(get_alert_page(new_alert._id))



@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.deactivate()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    status_update = alert.activate()
    # if it is reactivated - need to update also the price
    if status_update:
        alert.load_item_price()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.get_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)

@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    pass

@alert_blueprint.route('check_price/<string:alert_id>')
@user_decorators.requires_login
def check_alert_price(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.load_item_price()
    # we have end entry point that present the item and we need to redirect to it
    # pay attentuion that this method is in current view - therefore it start with '.'
    return redirect(url_for('.get_alert_page', alert_id=alert._id))

@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.remove_from_mongo()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/update/<string:alert_id>', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def update_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    item = Item.get_by_id(alert.item._id)
    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/edit_alert.html', alert=alert)
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)

# 2 types of entries
# - first time to present the login page --> GET
# - second time to process the populated form

@user_blueprint.route('/login', methods = ['GET', 'POST'])
def user_login():
    if request.method == 'POST':
        # check if login is valid
        email = request.form['email']
        # decided not to save hashed password
        #password = request.form['hashed']
        password = request.form['password']
        # present the correct  exception message
        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                #url_for return in a service the url of specific method - start with dot"." for current file
                #in this case the method in this file called user_alerts
                # so redurect to the new URL
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message


    # in case of GET - we need to present the login screen
    # in case of post - in case the user is invalid - TODO send an error to the users

    return render_template("users/login.html")

@user_blueprint.route('/register', methods = ['GET', 'POST'])
def user_register():
    if request.method == 'POST':
        # check if login is valid
        email = request.form['email']
        # decided not to save hashed password
        # password = request.form['hasshed']
        password = request.form['password']
        name = request.form['name']

        # present the correct  exception message
        try:
            if User.register_user(name, email, password):
                session['email'] = email
                # url_for return in a service the url of specific method - start with dot"." for current file
                # in this case the method in this file called user_alerts
                # so redurect to the new URL
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    # in case of GET - we need to present the login screen
    # in case of post - in case the user is invalid - TODO send an error to the users

    return render_template("users/register.html")

@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.get_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alerts.html', alerts=alerts)

@user_blueprint.route('/logout')
def user_logout():
    # remove the email session
    session['email'] = None

    return redirect(url_for('home'))

@user_blueprint.route('/check/alerts/<string_user_id>')
def check_user_alerts(user_id):
    pass

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Services</title>

    {% include 'html_dependencies.html' %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <i class="fas fa-home"></i> Pricing
        </a>
    </nav>
    <div class="container">
        <div class="d-flex p-2 bd-highlight">

            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="nav navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.user_login') }}">
                            <i class="fas fa-sign-in-alt"></i> Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.user_logout') }}">
                            <i class="fas fa-sign-out-alt"></i> Logout</a>
                    </li>

                    <li class="nav-item">
                        <!-- replace the "/register" end point with jinga code that start with blueprint name + method name that linked t othe end point
                        in this case it is users.register_users() -->
                        <a class="nav-link" href="{{ url_for('users.user_register') }}">
                            <i class="far fa-registered"></i> Sign Up</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('stores.index') }}">
                            <i class="fas fa-store"></i> Stores</a>
                    </li>

                    {% if 'email' in session.keys() and session['email'] != None %}

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.user_alerts') }}">
                            <i class="fas fa-exclamation-triangle"></i>My Alerts</a>
                    </li>

                    {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('alerts.index') }}">
                            <i class="fas fa-store"></i> Alerts</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
        </div>


</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

src/templates/home.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>

<div class="jumbotron">
  <h1 class="display-4">Pricing Services</h1>
  <p class="lead">This is a simple app that can scan online store websites to alert
       you of price drops in items that interest you.</p>
  <hr class="my-4">
  <p>Just sign up, and get started by adding the URL of an item that you wish to track.
      We'll do the rest!</p>
  <a class="btn btn-primary btn-lg" href="{{ url_for('users.user_register') }}" role="button">Sign up</a>
</div>

{% endblock %}

src/templates/html_dependencies.html
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">