src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, make_response, url_for, redirect

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators
import src.models.stores.error as StoreErrors

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route("/")
def index():
    alerts = Alert.get_alerts()
    return render_template('alerts/alert_index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def create_alert():

    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/create_alert.html')
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])
        item_name = request.form['name']
        item_url = request.form['url']
        try:
            item = Item(item_name, item_url)
        except StoreErrors.StoreError as e:
            return e.message
        #get the user details from DB by session email
        user_email = session['email']

        # create the new blog in DB
        new_alert = Alert(user_email, price_limit, item._id)

        new_alert.load_item_price()


        # save to DB only after alert was created
        item.save_to_mongo()

        # will prepare the data of existing alert - based on above method
        return make_response(get_alert_page(new_alert._id))



@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.deactivate()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    status_update = alert.activate()
    # if it is reactivated - need to update also the price
    if status_update:
        alert.load_item_price()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.get_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)

@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    pass

@alert_blueprint.route('check_price/<string:alert_id>')
@user_decorators.requires_login
def check_alert_price(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.load_item_price()
    # we have end entry point that present the item and we need to redirect to it
    # pay attentuion that this method is in current view - therefore it start with '.'
    return redirect(url_for('.get_alert_page', alert_id=alert._id))

@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.remove_from_mongo()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/update/<string:alert_id>', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def update_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    item = Item.get_by_id(alert.item._id)
    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/edit_alert.html', alert=alert)
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)

# 2 types of entries
# - first time to present the login page --> GET
# - second time to process the populated form

@user_blueprint.route('/login', methods = ['GET', 'POST'])
def user_login():
    if request.method == 'POST':
        # check if login is valid
        email = request.form['email']
        # decided not to save hashed password
        #password = request.form['hashed']
        password = request.form['password']
        # present the correct  exception message
        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                #url_for return in a service the url of specific method - start with dot"." for current file
                #in this case the method in this file called user_alerts
                # so redurect to the new URL
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message


    # in case of GET - we need to present the login screen
    # in case of post - in case the user is invalid - TODO send an error to the users

    return render_template("users/login.html")

@user_blueprint.route('/register', methods = ['GET', 'POST'])
def user_register():
    if request.method == 'POST':
        # check if login is valid
        email = request.form['email']
        # decided not to save hashed password
        # password = request.form['hasshed']
        password = request.form['password']
        name = request.form['name']

        # present the correct  exception message
        try:
            if User.register_user(name, email, password):
                session['email'] = email
                # url_for return in a service the url of specific method - start with dot"." for current file
                # in this case the method in this file called user_alerts
                # so redurect to the new URL
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    # in case of GET - we need to present the login screen
    # in case of post - in case the user is invalid - TODO send an error to the users

    return render_template("users/register.html")

@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.get_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alerts.html', alerts=alerts)

@user_blueprint.route('/logout')
def user_logout():
    # remove the email session
    session['email'] = None

    return redirect(url_for('home'))

@user_blueprint.route('/check/alerts/<string_user_id>')
def check_user_alerts(user_id):
    pass

src/templates/users/alerts.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br xmlns="http://www.w3.org/1999/html">
<h1>User Alerts Page</h1>

     <!-- we will use Jinga control flows -->
    {% if alerts|length > 0 %}
    <div class="list-group">
        {% for alert in alerts %}
        <a href="{{ url_for('alerts.get_alert_page', alert_id = alert._id) }}" class="list-group-item list-group-item-action
                            {{ 'list-group-item-warning' if not alert.is_active else '' }}">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Alert for {{ alert.item.name }}</h5>
                <small>Price Limit: {{ alert.price_limit}}</small>
            </div>
            <p class="mb-1">
                Last Checked: <Strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M")}} </Strong>
            </p>
            <p class="mb-1">
                Received Price: <Strong>{{ alert.item.price}} </Strong>
            </p>
            <div class="d-flex w-100 justify-content-between">
                <small>User: {{ alert.user_email }}</small>
                {% if not alert.is_active %}
                <small>Alert is <strong>Not Active </strong><i class="far fa-times-circle"></i></small>
                {% endif %}
            </div>
        </a>
        {% endfor %}
    </div>
    {% else %}
         <h3>There are no Alerts</h3>
    {% endif %}
    <br>
    <!-- add button to create new alert in the context of the user -->
    <a class="btn btn-primary" href="{{ url_for('alerts.create_alert')}}"><i class="far fa-plus-square"></i> Create New</a>

{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<br>

    <h1>User Login</h1>

    <form id="register-form" action="{{ url_for('users.user_login') }}" method="post" class ="form-size">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<br>

    <h1>User Sign Up</h1>

    <form id="register-form" action="{{ url_for('users.user_register') }}" method="post" class ="form-size">
        <div class="form-group">
            <label for="name">User Name</label>
            <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="Enter user name">
            <small id="nameHelp" class="form-text text-muted">We'll never share your user with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>

{% endblock %}