src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, make_response, url_for, redirect

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators
import src.models.stores.error as StoreErrors

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route("/")
def index():
    alerts = Alert.get_alerts()
    return render_template('alerts/alert_index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def create_alert():

    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/create_alert.html')
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])
        item_name = request.form['name']
        item_url = request.form['url']
        try:
            item = Item(item_name, item_url)
        except StoreErrors.StoreError as e:
            return e.message
        #get the user details from DB by session email
        user_email = session['email']

        # create the new blog in DB
        new_alert = Alert(user_email, price_limit, item._id)

        new_alert.load_item_price()


        # save to DB only after alert was created
        item.save_to_mongo()

        # will prepare the data of existing alert - based on above method
        return make_response(get_alert_page(new_alert._id))



@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.deactivate()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    status_update = alert.activate()
    # if it is reactivated - need to update also the price
    if status_update:
        alert.load_item_price()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.get_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)

@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    pass

@alert_blueprint.route('check_price/<string:alert_id>')
@user_decorators.requires_login
def check_alert_price(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.load_item_price()
    # we have end entry point that present the item and we need to redirect to it
    # pay attentuion that this method is in current view - therefore it start with '.'
    return redirect(url_for('.get_alert_page', alert_id=alert._id))

@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    alert.remove_from_mongo()
    #redirect to the next entry point
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/update/<string:alert_id>', methods=['POST', 'GET'])
@user_decorators.requires_login
# add new decorator that will be in charge for validating if user is already logged in
# if not it will redirect it to login page
def update_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    item = Item.get_by_id(alert.item._id)
    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('alerts/edit_alert.html', alert=alert)
    else:
        # get from the request the newly created alert details
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

src/templates/alerts/alert.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<div class="card text-center">
  <div class="card-header">
    Alert for {{ alert.item.name }}
  </div>
  <div class="card-body">
    <h5 class="card-title">Last Price found: {{ alert.item.price}}</h5>
    <p class="card-text"> Price Limit: {{ alert.price_limit}}</p>
    <p class="card-text"> User: {{ alert.user_email }}</p>
    <a href="{{ alert.item.url }}" class="btn btn-success">Visit Site</a>
    {% if alert.is_active %}
    <a href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" class="btn btn-danger">Deactivate Alert</a>
    <a href="{{ url_for('alerts.update_alert', alert_id=alert._id) }}" class="btn btn-warning">Edit Alert</a>
    {% else %}
     <a href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" class="btn btn-warning">Activate Alert</a>
    <a href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" class="btn btn-danger">Delete Alert</a>
    {% endif %}
    <a href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" class="btn btn-info">Check Price</a>
  </div>
  <div class="card-footer text-muted">
    <div class="d-flex w-100 justify-content-between">
   Last Checked: {{ alert.last_checked.strftime("%d-%m-%Y at %H:%M")}}
    {% if alert.is_active %}
    <strong> Status is Active </strong>
    {% else %}
    <strong>Alert Status is In-Active </strong>
    {% endif %}
    </div>
  </div>
</div>

{% endblock %}

src/templates/alerts/alert_index.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
    <br>
    <h1>Alert Index</h1>

     <!-- we will use Jinga control flows -->
    {% if alerts|length > 0 %}
        <div class="list-group">
            {% for alert in alerts %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id = alert._id) }}" class="list-group-item list-group-item-action
               {{ 'list-group-item-warning' if not alert.is_active else '' }}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Alert for {{ alert.item.name }}</h5>
                    <small>Price Limit: {{ alert.price_limit}}</small>
                </div>
                <p class="mb-1">
                    Last Checked: <Strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M")}} </Strong>
                </p>
                <div class="d-flex w-100 justify-content-between">
                    <p class="mb-1">
                        Received Price: <Strong>{{ alert.item.price}} </Strong>
                    </p>
                    {% if not alert.is_active %}
                    <p><small>Alert is <strong>Not Active </strong><i class="far fa-times-circle"></i></small></p>
                    {% endif %}
                </div>
            </a>
        {% endfor %}
        </div>
    {% else %}
         <h3>There are no Alerts</h3>
    {% endif %}
    <br>

{% endblock %}

src/templates/alerts/create_alert.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<h1>Create Alert
 <small>Used for create new alert for specific item</small></h1>
 <br>

    <form id="create-alert-form" action="{{ url_for('alerts.create_alert') }}" method="post" class ="form-size">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter the Alert/Item name">
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" aria-describedby="urlHelp" placeholder="http://www...">
            <small id="urlHelp" class="form-text text-muted">Enter the URL of the item to explore.</small>
        </div>
        <div class="form-group">
            <label for="price_limit">Alert limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" aria-describedby="priceLimitHelp" placeholder="45.0">
            <small id="priceLimitHelp" class="form-text text-muted">You will get an email if the price will reach below this limit.</small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>


{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<h1>Edit Alert
 <small>Used for update existing alert for specific item</small></h1>
 <br>

    <form id="update-alert-form"  method="post" class ="form-size">
        <div class="form-group">
            <label for="price_limit">Alert limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" aria-describedby="priceLimitHelp" placeholder="45.0" value="{{ alert.price_limit }}">
            <small id="priceLimitHelp" class="form-text text-muted">You will get an email if the price will reach below this limit.</small>
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
    </form>


{% endblock %}