src/models/stores/views.py
from flask import Blueprint, render_template, request, make_response, url_for, redirect, json
import src.models.users.decorators as user_decorators
from src.models.stores.store import Store

store_blueprint = Blueprint('stores', __name__)

@store_blueprint.route("/")
def index():
    stores = Store.get_stores()
    return render_template('stores/store_index.html', stores=stores)



@store_blueprint.route('/new', methods=['POST', 'GET'])
@user_decorators.requires_admin_priv
def create_store():

    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    if request.method == 'GET':
        return render_template('stores/create_store.html')
    else:
        # get from the request the newly created alert details
        name = request.form['name']
        url_prefix = request.form['url']
        tag_name = request.form['tag_name']
        # need to format the query as json
        query = json.load(request.form['query'])

        store = Store(name, url_prefix, tag_name, query)

        store.save_to_mongo()

        return redirect(url_for('stores.index'))


@store_blueprint.route('/<string:store_id>')
def get_store_page(store_id):
    store = Store.get_by_id(store_id)
    return render_template('stores/store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_priv
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    store.remove_from_mongo()
    #redirect to the next entry point
    return redirect(url_for('stores.index'))


@store_blueprint.route('/update/<string:store_id>', methods=['POST', 'GET'])
@user_decorators.requires_admin_priv
def update_store(store_id):
    # in case we receive GET - this is the first time the page is opened
    # in case we receive  POST - we have the details
    store = Store.get_by_id(store_id)
    if request.method == 'GET':
        return render_template('stores/edit_store.html', store=store)
    else:
        # get from the request the newly created alert details
        name = request.form['name']
        url_prefix = request.form['url']
        tag_name = request.form['tag_name']
        query = request.form['query']

        # upload from DB the store details and then set them with new data

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query
        store.save_to_mongo()
        return redirect(url_for('stores.index'))

src/templates/stores/create_store.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<h1>Create Store Page</h1>
<br>
<form id="create-store-form"  method="post" class ="form-size">
 <div class="form-group">
  <label for="name">Store name</label>
  <input type="text" class="form-control" id="name" name="name" placeholder="Enter name for store">
 </div>
 <div class="form-group">
  <label for="url">Store URL</label>
  <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
 </div>
 <div class="form-group">
  <label for="url">Tag name</label>
  <input type="text" class="form-control" id="tag_name" name="tag_name" aria-describedby="tagHelp" placeholder="Tag Name">
  <small id="tagHelp" class="form-text text-muted">populate the tag name that hold the price in store URL</small>
 </div>
 <div class="form-group">
  <label for="query">Query</label>
  <input type="text" class="form-control" id="query" name="query" aria-describedby="queryHelp" placeholder='{"id": "price-now"}'>
  <small id="queryHelp" class="form-text text-muted">what Json query we need to use in order to find the price</small>
 </div>
 <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<h1>Edit Store Page</h1>
<br>

<!-- this page is saem as create store, but in addition in this form we add also the value from the store by populate the value for each field -->
<form id="edit-store-form"  method="post" class ="form-size">
 <div class="form-group">
  <label for="name">Store name</label>
  <input type="text" class="form-control" id="name" name="name" placeholder="Enter name for store" value="{{ store.name }}">
 </div>
 <div class="form-group">
  <label for="url">Store URL</label>
  <input type="text" class="form-control" id="url" name="url" placeholder="http://..." value="{{ store.url_prefix }}">
 </div>
 <div class="form-group">
  <label for="tag_name">Tag name</label>
  <input type="text" class="form-control" id="tag_name" name="tag_name" aria-describedby="tagHelp" placeholder="Tag Name" value="{{ store.tag_name }}">
  <small id="tagHelp" class="form-text text-muted">populate the tag name that hold the price in store URL</small>
 </div>
 <div class="form-group">
  <label for="query">Query</label>
  <input type="text" class="form-control" id="query" name="query" aria-describedby="queryHelp" placeholder='{"id": "price-now"}' value="{{ store.query }}">
  <small id="queryHelp" class="form-text text-muted">what Json query we need to use in order to find the price</small>
 </div>
 <button type="submit" class="btn btn-warning">Update</button>
</form>

{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<div class="card text-center">
  <div class="card-header">
    {{ store.name }} Store
  </div>
  <div class="card-body">
        <h5 class="card-title">Store URL: {{ store.url_prefix }}</h5>
        <p class="card-text"> Price Taq: {{ store.tag_name }}</p>
        <p class="card-text"> Query: {{ store.query }}</p>
        <a href="{{ store.url_prefix }}" class="btn btn-success">Visit Store</a>
        {% if session['email'] in config.ADMINS %}
            <a href="{{ url_for('stores.delete_store', store_id=store._id) }}" class="btn btn-danger">Delete Store</a>
            <a href="{{ url_for('stores.update_store', store_id=store._id) }}" class="btn btn-info">Update Store</a>
        {% endif %}
  </div>
</div>


{% endblock %}

name, url_prefix, tag_name, query

src/templates/stores/store_index.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
    <br>
    <h1>Store Index</h1>

     <!-- we will use Jinga control flows -->
    {% if stores|length > 0 %}
        <div class="list-group">
            {% for store in stores %}
            <a href="{{ url_for('stores.get_store_page', store_id = store._id) }}" class="list-group-item list-group-item-action">
            <h5 class="mb-1">{{ store.name }} Store</h5>

            <p>All store products should  start with {{ store.url_prefix}}</p>

        </a>
        {% endfor %}
    </div>
    {% else %}
         <h3>There are no Stores</h3>
    {% endif %}
    <br>
    <!-- add button to create new alert in the context of the user -->
    <!-- add button is valid only for admin -->
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-primary" href="{{ url_for('stores.create_store')}}"><i class="far fa-plus-square"></i> Create New</a>
    {% endif %}


{% endblock %}

src/templates/stores/store_list.html
{% extends "base.html" %}
<!-- override the block content -->
{% block content %}
<br>
<h1>Store List Page</h1>
 <p>Nothing here yet!</p>


{% endblock %}